# Data loading: GEO download, file format conversion, R/RDS import.

from kosmic.scrna.load.converters import (
    detect_file_format,
    looks_like_barcode,
    detect_matrix_orientation,
    convert_matrix_to_h5ad,
    csv_to_h5ad,
    mtx_to_h5ad,
    tsv_to_h5ad,
    h5_to_h5ad,
    load_10x_folder,
    assemble_h5ad_from_r_export,
    build_adata_summary,
    load_h5ad_with_summary,
    find_10x_files,
    load_prefixed_10x,
    load_10x_multi_sample,
)
from kosmic.scrna.load.download import (
    query_geo_files,
    download_file,
    extract_archive,
    find_sample_tarballs,
    extract_tarball,
    load_multi_sample_10x,
)
from kosmic.scrna.load.rds_converter import (
    find_r_executable,
    generate_rds_export_script,
    run_rds_to_intermediate,
    load_rds_rds2py,
    load_rds_pyreadr,
    load_rds_via_r,
    load_rds,
)

__all__ = [
    "detect_file_format",
    "looks_like_barcode",
    "detect_matrix_orientation",
    "convert_matrix_to_h5ad",
    "csv_to_h5ad",
    "mtx_to_h5ad",
    "tsv_to_h5ad",
    "h5_to_h5ad",
    "load_10x_folder",
    "assemble_h5ad_from_r_export",
    "build_adata_summary",
    "load_h5ad_with_summary",
    "find_10x_files",
    "load_prefixed_10x",
    "load_10x_multi_sample",
    "query_geo_files",
    "download_file",
    "extract_archive",
    "find_sample_tarballs",
    "extract_tarball",
    "load_multi_sample_10x",
    "find_r_executable",
    "generate_rds_export_script",
    "run_rds_to_intermediate",
    "load_rds_rds2py",
    "load_rds_pyreadr",
    "load_rds_via_r",
    "load_rds",
]
